language: python
matrix:
  include:
  - python: 2.6
    env: TOXENV=py26
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
    dist: xenial
    sudo: true  # required for py37
  - python: pypy2.7-5.10.0
    env: TOXENV=pypy
  - python: pypy3.5-5.10.0
    env: TOXENV=pypy3
  - python: 3.6
    env: TOXENV=flake8
  - python: 3.6
    env: TOXENV=setup.py
  - python: 3.6
    env: TOXENV=nodeps
cache:
  pip: true
  directories:
  - $HOME/.cache/pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
notifications:
  email: false
install:
- pip install tox
- pip install .
script:
- tox
