language: python
env:
  global:
    - PIP_CACHE_DIR="$HOME/.cache/pip"  # unify pip cache location for all platforms
cache:
  pip: true
  directories:
  - $HOME/.cache/pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
notifications:
  email: false
stages:
- check
- test
- name: deploy
  if: repo = casperdcl/git-fame AND NOT type = pull_request
jobs:
  include:
  - stage: test
    name: py2.6
    python: 2.6
    env: TOXENV=py26
    dist: trusty
  - name: py2.7
    python: 2.7
    env: TOXENV=py27
  - name: py3.4
    python: 3.4
    env: TOXENV=py34
  - name: py3.5
    python: 3.5
    env: TOXENV=py35
  - name: py3.6
    python: 3.6
    env: TOXENV=py36
  - name: py3.7
    python: 3.7
    env: TOXENV=py37
  - name: py3.8
    python: 3.8
    env: TOXENV=py38
  - name: pypy2.7
    python: pypy
    env: TOXENV=pypy
  - name: pypy3
    python: pypy3
    env: TOXENV=pypy3
  - stage: check
    name: style
    python: 3.7
    env: TOXENV=flake8
  - name: setup
    python: 3.7
    env: TOXENV=setup.py
  - name: nodeps
    python: 3.7
    env: TOXENV=nodeps
  - stage: deploy
    name: PyPI and GitHub
    python: 3.7
    addons:
      apt:
        packages:
        - pandoc
    install:
    script:
    - pip install .[dev]
    - make build
    - openssl aes-256-cbc -K $encrypted_88867ca921c3_key
      -iv $encrypted_88867ca921c3_iv -in .meta/.casperdcl.gpg.enc
      -out .casperdcl.gpg -d
    - gpg --import .casperdcl.gpg
    - rm .casperdcl.gpg
    - git log --pretty='format:- %s%n%b---' $(git tag --sort=creatordate | tail -n2 | head -n1)..HEAD > CHANGES.md
    deploy:
    - provider: script
      script: twine upload -s -i casper.dcl@physics.org dist/git?fame-*
      skip_cleanup: true
      on:
        tags: true
    - provider: releases
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: dist/git?fame-*.whl*
      skip_cleanup: true
      draft: true
      name: git-fame $TRAVIS_TAG stable
      edge: true
      tag_name: $TRAVIS_TAG
      target_commitish: $TRAVIS_COMMIT
      release_notes_file: CHANGES.md
      on:
        tags: true
  - name: docker
    python: 3.7
    services:
    - docker
    install:
    script:
    - echo "$DOCKER_PWD" | docker login -u $DOCKER_USR --password-stdin
    - echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u $GITHUB_USR --password-stdin
    - make -B docker
    - |
      if [[ -n "$TRAVIS_TAG" ]]; then
      docker tag casperdcl/git-fame:latest casperdcl/git-fame:${TRAVIS_TAG#v}
      docker tag casperdcl/git-fame:latest docker.pkg.github.com/casperdcl/git-fame/git-fame:${TRAVIS_TAG#v} ; fi
    - docker tag casperdcl/git-fame:latest casperdcl/git-fame:devel
    - docker tag casperdcl/git-fame:latest docker.pkg.github.com/casperdcl/git-fame/git-fame:latest
    - docker tag casperdcl/git-fame:latest docker.pkg.github.com/casperdcl/git-fame/git-fame:devel
    deploy:
    - provider: script
      script: docker push casperdcl/git-fame:${TRAVIS_TAG#v}
      on:
        tags: true
    - provider: script
      script: 'docker push docker.pkg.github.com/casperdcl/git-fame/git-fame:${TRAVIS_TAG#v} || :'
      on:
        tags: true
    - provider: script
      script: docker push casperdcl/git-fame:latest
    - provider: script
      script: 'docker push docker.pkg.github.com/casperdcl/git-fame/git-fame:latest || :'
    - provider: script
      script: docker push casperdcl/git-fame:devel
      on:
        branch: devel
    - provider: script
      script: 'docker push docker.pkg.github.com/casperdcl/git-fame/git-fame:devel || :'
      on:
        branch: devel
  - name: snap
    python: 3.7
    addons:
     snaps:
     - name: snapcraft
       channel: stable
       confinement: classic
     - name: review-tools
       channel: stable
     - name: lxd
       channel: stable
    env:
    - SNAPCRAFT_IMAGE_INFO: |
        '{"build_url": "$TRAVIS_JOB_WEB_URL"}'
    - SNAPCRAFT_BUILD_ENVIRONMENT: lxd
    - SNAPCRAFT_BUILD_INFO: 1  # https://snapcraft.io/blog/introducing-developer-notifications-for-snap-security-updates
    before_install:
    - sudo usermod --append --groups lxd $USER
    - sudo /snap/bin/lxd.migrate -yes
    - sudo /snap/bin/lxd waitready
    - sudo /snap/bin/lxd init --auto
    install:
    - make snapcraft.yaml
    script:
    - sg lxd -c snapcraft
    after_failure:
    - sudo journalctl -u snapd
    deploy:
    - provider: snap
      snap: git-fame*.snap
      channel: stable
      skip_cleanup: true
      on:
        tags: true
    - provider: snap
      snap: git-fame*.snap
      channel: candidate
      skip_cleanup: true
    - provider: snap
      snap: git-fame*.snap
      channel: edge
      skip_cleanup: true
      on:
        branch: devel
before_install:
- git fetch --tags
install:
- pip install tox
- pip install .
script:
- tox
