language: python
matrix:
  include:
  - python: 2.6
    env: TOXENV=py26
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
    dist: xenial
    sudo: true  # required for py37, docker
    services:
    - docker
    after_success:
    - echo "$DOCKER_PWD" | docker login -u $DOCKER_USR --password-stdin
    - make -B docker
    - |
      if [[ -n "$TRAVIS_TAG" ]]; then
      docker tag casperdcl/git-fame:latest casperdcl/git-fame:$TRAVIS_TAG ; fi
    - docker tag casperdcl/git-fame:latest casperdcl/git-fame:devel
    - pip install .[dev]
    - make build
    - openssl aes-256-cbc -K $encrypted_88867ca921c3_key
      -iv $encrypted_88867ca921c3_iv -in .casperdcl.gpg.enc
      -out .casperdcl.gpg -d
    - gpg --import .casperdcl.gpg
    - rm .casperdcl.gpg
    deploy:
    - provider: script
      script: twine upload -s -i casper.dcl@physics.org dist/git-fame-*
      skip_cleanup: true
      on:
        tags: true
    - provider: releases
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: dist/git-fame-*.whl*
      skip_cleanup: true
      draft: true
      name: git-fame v$TRAVIS_TAG stable
      on:
        tags: true
    - provider: script
      script: docker push casperdcl/git-fame:$TRAVIS_TAG
      on:
        tags: true
    - provider: script
      script: docker push casperdcl/git-fame:latest
    - provider: script
      script: docker push casperdcl/git-fame:devel
      on:
        branch: devel
  - python: pypy2.7-5.10.0
    env: TOXENV=pypy
  - python: pypy3.5-5.10.0
    env: TOXENV=pypy3
  - python: 3.6
    env: TOXENV=flake8
  - python: 3.6
    env: TOXENV=setup.py
  - python: 3.6
    env: TOXENV=nodeps
cache:
  pip: true
  directories:
  - $HOME/.cache/pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
notifications:
  email: false
install:
- pip install tox
- pip install .
script:
- tox
